language: rust
script: cargo run

env:
  global:
    - RUST_LOG=debug,selectors=info,rustls=info,html5ever=info

cache:
  directories:
    - results # So we don't have to check all the things every time