name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-md:
    runs-on: ubuntu-latest
    name: Lint Markdown content
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Markdown lint for README
        uses: docker://avtodev/markdown-lint:v1
        with:
          config: ./.markdownlint.json
          args: ./README.md
  lint-editorconfig:
    runs-on: ubuntu-latest
    name: Lint for editorconfig violations
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Check for editorconfig violations
        uses: editorconfig-checker/action-editorconfig-checker@v1
